'use client'
import { createContext, useContext, useState, ReactNode } from 'react'

type Lang = 'en' | 'sv'

const translations = {
  en: {
    nav_bikes: 'Bikes',
    nav_pricing: 'Pricing',
    nav_book: 'Book',
    hero_badge: 'Uppsala University Students',
    hero_title: 'Your bike for Uppsala life',
    hero_sub: 'Semester, monthly, weekly or daily — easy booking, flexible pickup.',
    btn_book: 'Book now',
    btn_browse: 'Browse bikes',
    section_bikes: 'Our bikes',
    section_pricing: 'Pricing',
    section_book: 'Book a bike',
    section_faq: 'FAQ',
    type_single: 'Single speed',
    type_3speed: '3-speed',
    type_multi: '6 / 7-speed',
    status_available: 'Available',
    status_rented: 'Rented out',
    status_maintenance: 'In service',
    per_day: '/ day',
    from: 'from',
    plan_day: 'Daily',
    plan_week: 'Weekly',
    plan_month: 'Monthly',
    plan_semester: 'Semester',
    plan_day_sub: 'Flexible',
    plan_week_sub: 'Save ~20%',
    plan_month_sub: 'Popular',
    plan_semester_sub: 'Best value · 5 months',
    form_name: 'Full name',
    form_email: 'Student email',
    form_bike: 'Bike',
    form_plan: 'Rental plan',
    form_date: 'Pickup date',
    form_location: 'Pickup location',
    form_notes: 'Notes (optional)',
    form_notes_ph: 'e.g. your height, special requests',
    form_submit: 'Submit booking',
    form_footer: 'We\'ll confirm by email within 24 hours · Payment on pickup (Swish / cash)',
    form_success: 'Booking submitted! We\'ll email you at ',
    form_error: 'Please fill in name, email and pickup date.',
    faq_q1: 'Is a deposit required?',
    faq_a1: 'Yes, 500 SEK deposit required. Returned within 7 working days after you return the bike.',
    faq_q2: 'What if the bike breaks?',
    faq_a2: 'Normal wear and tear is covered. Contact us by email or WeChat to arrange a repair.',
    faq_q3: 'Can I return early?',
    faq_a3: 'Yes. Semester and monthly rentals are prorated — we refund the unused days.',
    faq_q4: 'Where do I pick up?',
    faq_a4: 'Currently at Ekonomikum, Ångström and BMC. Choose your preferred point when booking.',
    loc_ekonomikum: 'Ekonomikum (Main campus)',
    loc_angstrom: 'Ångström (Engineering)',
    loc_bmc: 'BMC (Medical campus)',
    footer_contact: 'WeChat support',
    footer_email: 'Email us',
    view_details: 'View details',
    back: '← Back',
    bike_detail_book: 'Book this bike',
    sek: 'SEK',
  },
  sv: {
    nav_bikes: 'Cyklar',
    nav_pricing: 'Priser',
    nav_book: 'Boka',
    hero_badge: 'För studenter vid Uppsala universitet',
    hero_title: 'Din cykel för livet i Uppsala',
    hero_sub: 'Termin, månad, vecka eller dag — enkel bokning, flexibel upphämtning.',
    btn_book: 'Boka nu',
    btn_browse: 'Se cyklar',
    section_bikes: 'Våra cyklar',
    section_pricing: 'Priser',
    section_book: 'Boka en cykel',
    section_faq: 'Vanliga frågor',
    type_single: 'Enkelväxlad',
    type_3speed: '3-växlad',
    type_multi: '6 / 7-växlad',
    status_available: 'Tillgänglig',
    status_rented: 'Uthyrd',
    status_maintenance: 'Service',
    per_day: '/ dag',
    from: 'från',
    plan_day: 'Per dag',
    plan_week: 'Per vecka',
    plan_month: 'Per månad',
    plan_semester: 'Termin',
    plan_day_sub: 'Flexibelt',
    plan_week_sub: 'Spara ~20%',
    plan_month_sub: 'Populärt',
    plan_semester_sub: 'Bäst värde · 5 månader',
    form_name: 'Fullständigt namn',
    form_email: 'Student-e-post',
    form_bike: 'Cykel',
    form_plan: 'Hyresplan',
    form_date: 'Upphämtningsdatum',
    form_location: 'Upphämtningsplats',
    form_notes: 'Anteckningar (valfritt)',
    form_notes_ph: 't.ex. din längd, önskemål',
    form_submit: 'Skicka bokning',
    form_footer: 'Vi bekräftar via e-post inom 24 timmar · Betalning vid upphämtning (Swish / kontant)',
    form_success: 'Bokning skickad! Vi mailar dig på ',
    form_error: 'Fyll i namn, e-post och upphämtningsdatum.',
    faq_q1: 'Krävs det en deposition?',
    faq_a1: '500 SEK i deposition krävs. Återbetalas inom 7 arbetsdagar efter att du lämnar tillbaka cykeln.',
    faq_q2: 'Vad händer om cykeln går sönder?',
    faq_a2: 'Normalt slitage täcks. Kontakta oss via e-post eller WeChat för reparation.',
    faq_q3: 'Kan jag lämna tillbaka i förtid?',
    faq_a3: 'Ja. Termins- och månadsuthyrning beräknas proportionellt — vi återbetalar oanvända dagar.',
    faq_q4: 'Var hämtar jag ut cykeln?',
    faq_a4: 'För närvarande vid Ekonomikum, Ångström och BMC. Välj vid bokning.',
    loc_ekonomikum: 'Ekonomikum (Huvudcampus)',
    loc_angstrom: 'Ångström (Teknik)',
    loc_bmc: 'BMC (Medicin)',
    footer_contact: 'WeChat-support',
    footer_email: 'Maila oss',
    view_details: 'Visa detaljer',
    back: '← Tillbaka',
    bike_detail_book: 'Boka denna cykel',
    sek: 'SEK',
  }
}

type T = typeof translations.en
const LangContext = createContext<{ lang: Lang; t: T; setLang: (l: Lang) => void }>({
  lang: 'en', t: translations.en, setLang: () => {}
})

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')
  return (
    <LangContext.Provider value={{ lang, t: translations[lang], setLang }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
