'use client'
import { createContext, useContext, useState, ReactNode } from 'react'

type Lang = 'en' | 'sv'

const translations = {
  en: {
    nav_bikes: 'Bikes',
    nav_book: 'Book',
    hero_badge: 'Uppsala University Students',
    hero_title: 'Your bike for Uppsala life',
    hero_sub: 'Monthly or semester rental — easy booking, flexible pickup.',
    btn_book: 'Book now',
    btn_browse: 'Browse bikes',
    section_bikes: 'Our bikes',
    section_book: 'Book a bike',
    section_faq: 'FAQ',
    type_single: 'Single speed',
    type_3speed: '3-speed',
    type_multi: '6 / 7-speed',
    status_available: 'Available',
    status_rented: 'Rented out',
    status_maintenance: 'In service',
    per_day: '/ day',
    from: 'from',
    plan_month: 'Monthly',
    plan_semester: 'Semester',
    plan_month_sub: 'Flexible',
    plan_semester_sub: 'Best value · 5 months',
    form_name: 'Full name',
    form_email: 'Email',
    form_bike: 'Bike',
    form_plan: 'Rental plan',
    form_date: 'Pickup date',
    form_location: 'Pickup location',
    form_notes: 'Notes (optional)',
    form_notes_ph: 'e.g. your height, special requests',
    form_submit: 'Submit booking',
    form_footer: "We'll confirm by email within 24 hours · Payment on pickup (Swish / cash)",
    form_success: "Booking submitted! We'll email you at ",
    form_error: 'Please fill in name, email and pickup date.',
    faq_q1: 'Is a deposit required?',
    faq_a1: 'Yes, a 500 SEK deposit is required and will be collected at pickup. It will be returned in full when you return the bike in its original condition.',
    faq_q2: 'What if the bike breaks?',
    faq_a2: 'Please inspect the bike carefully before accepting it — any existing damage should be noted at the time of pickup. Damage occurring during the rental period will be assessed and repair costs charged accordingly. Full terms are outlined in the rental agreement.',
    faq_q3: 'Can I return early?',
    faq_a3: 'Yes, early returns are welcome. Your deposit will be returned in full. However, the rental fee already paid is non-refundable regardless of when you return the bike.',
    faq_q4: 'Where do I pick up?',
    faq_a4: 'Currently at Flogsta, Ekonomikum, Angstrom and BMC. Choose your preferred point when booking.',
    loc_flogsta: 'Flogsta',
    loc_ekonomikum: 'Ekonomikum (Main campus)',
    loc_angstrom: 'Angstrom (Engineering)',
    loc_bmc: 'BMC (Medical campus)',
    footer_contact: 'WeChat',
    footer_whatsapp: 'WhatsApp',
    footer_email: 'Email',
    view_details: 'View details',
    back: '<- Back',
    bike_detail_book: 'Book this bike',
    sek: 'SEK',
    step_choose: 'Choose a bike',
    step_details: 'Fill in your details',
    wa_title: 'WhatsApp Support',
    wa_hours_label: 'Available hours',
    wa_hours: 'Mon - Fri, 09:30 - 17:30',
    wa_timezone: 'Uppsala time (CET/CEST)',
    wa_outside: 'Outside hours? Email us at',
    wa_open: 'Open WhatsApp',
    wa_close: 'Close',
  },
  sv: {
    nav_bikes: 'Cyklar',
    nav_book: 'Boka',
    hero_badge: 'For studenter vid Uppsala universitet',
    hero_title: 'Din cykel for livet i Uppsala',
    hero_sub: 'Manads- eller terminshyra - enkel bokning, flexibel upphamtning.',
    btn_book: 'Boka nu',
    btn_browse: 'Se cyklar',
    section_bikes: 'Vara cyklar',
    section_book: 'Boka en cykel',
    section_faq: 'Vanliga fragor',
    type_single: 'Enkelvaxlad',
    type_3speed: '3-vaxlad',
    type_multi: '6 / 7-vaxlad',
    status_available: 'Tillganglig',
    status_rented: 'Uthyrd',
    status_maintenance: 'Service',
    per_day: '/ dag',
    from: 'fran',
    plan_month: 'Per manad',
    plan_semester: 'Termin',
    plan_month_sub: 'Flexibelt',
    plan_semester_sub: 'Bast varde · 5 manader',
    form_name: 'Fullstandigt namn',
    form_email: 'E-post',
    form_bike: 'Cykel',
    form_plan: 'Hyresplan',
    form_date: 'Upphamtningsdatum',
    form_location: 'Upphamtningsplats',
    form_notes: 'Anteckningar (valfritt)',
    form_notes_ph: 't.ex. din langd, onskemал',
    form_submit: 'Skicka bokning',
    form_footer: 'Vi bekraftar via e-post inom 24 timmar · Betalning vid upphamtning (Swish / kontant)',
    form_success: 'Bokning skickad! Vi mailar dig pa ',
    form_error: 'Fyll i namn, e-post och upphamtningsdatum.',
    faq_q1: 'Kravs det en deposition?',
    faq_a1: 'Ja, en deposition pa 500 SEK kravs och betalas vid upphamtning. Den aterbetalas i sin helhet nar du lamnar tillbaka cykeln i originalskick.',
    faq_q2: 'Vad hander om cykeln gar sonder?',
    faq_a2: 'Inspektera cykeln noggrant innan du accepterar den - eventuella skador ska noteras vid upphamtningen. Skador som uppstar under hyresperioden bedoms och reparationskostnader debiteras i enlighet med detta. Fullstandiga villkor anges i hyreskontraktet.',
    faq_q3: 'Kan jag lamna tillbaka i fortid?',
    faq_a3: 'Ja, tidig aterlamnig ar valkommen. Din deposition aterbetalas i sin helhet. Hyresavgiften som redan betalats aterbetalas dock inte oavsett nar du lamnar tillbaka cykeln.',
    faq_q4: 'Var hamtar jag ut cykeln?',
    faq_a4: 'For narvarande vid Flogsta, Ekonomikum, Angstrom och BMC. Valj vid bokning.',
    loc_flogsta: 'Flogsta',
    loc_ekonomikum: 'Ekonomikum (Huvudcampus)',
    loc_angstrom: 'Angstrom (Teknik)',
    loc_bmc: 'BMC (Medicin)',
    footer_contact: 'WeChat',
    footer_whatsapp: 'WhatsApp',
    footer_email: 'E-post',
    view_details: 'Visa detaljer',
    back: '<- Tillbaka',
    bike_detail_book: 'Boka denna cykel',
    sek: 'SEK',
    step_choose: 'Valj en cykel',
    step_details: 'Fyll i dina uppgifter',
    wa_title: 'WhatsApp Support',
    wa_hours_label: 'Tillgangliga tider',
    wa_hours: 'Man - Fre, 09:30 - 17:30',
    wa_timezone: 'Uppsalatid (CET/CEST)',
    wa_outside: 'Utanfor arbetstid? Maila oss pa',
    wa_open: 'Oppna WhatsApp',
    wa_close: 'Stang',
  }
}

type T = typeof translations.en
const LangContext = createContext<{ lang: Lang; t: T; setLang: (l: Lang) => void }>({
  lang: 'en', t: translations.en, setLang: () => {}
})

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('en')
  return (
    <LangContext.Provider value={{ lang, t: translations[lang], setLang }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
